#!/usr/bin/ksh

ORACLE_SID=SIGMA
ORACLE_HOME=/home1/ora920/app/oracle/product/9.2.0
ORACLE_BASE=/home1/ora920/app/oracle
ORACLE_PATH=/home1/ora920/app/oracle/product/9.2.0/bin
ORACLE_TERM=vt100
TERM=vt100
ORA_NLS33=$ORACLE_HOME/ocommon/nls/admin/data
LD_LIBRARY_PATH=$ORACLE_HOME/lib:$ORACLE_HOME/jdbc/lib
CLASSPATH=$ORACLE_HOME/jdbc/lib/classes111.zip
TMPDIR=/var/tmp
PATH=$ORACLE_HOME/bin:/bin:/usr/bin:/usr/ccs/bin:/usr/lbin
export LD_LIBRARY_PATH ORA_NLS33 TMPDIR
export PATH ORACLE_SID ORACLE_HOME ORACLE_BASE ORACLE_TERM ORACLE_PATH

HOME=/home1/sigma
LOGNAME=sigma
PATH=/home1/sigma/bin:/home1/sigma/scr:/home1/sigma/sql:/home1/sigma/scr:/home1/ora920/app/oracle/product/9.2.0/bin:/usr/bin:/opt/SUNWspro/bin:/usr/ucb:/usr/ccs/bin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/openwin/bin:/etc:/opt/VRTSvmsa/jre/bin:/usr/java1.2/jre/lib/sparc:/home1/sqlb40/obacktrack/bin/:.
SHELL=/bin/ksh

cd /home1/sigma/pre_unif
fecha_proceso=`date '+%d/%m/%Y %T'`
echo 'Inicio del proceso: ' $fecha_proceso >> xcuenta.log

fecha8=`date '+%Y%m%d'`
fecha6=`date '+%Y%m'`
fecha4=`date '+%Y'`
mes=`date '+%m'`
ano=`date '+%Y'`
dia=`date '+%d'`

#fecha8='20070302'
#fecha6='200703'
#fecha4='2007'
#ano='2007'
#mes='03'
#dia='02'

fecha_ini=$fecha6'01'

echo "Carga Par metros" >> xcuenta.log

if [ $fecha_ini -eq $fecha8 ]
then
	if [ $mes -eq 01 ]
	then
		fecha4=$(($fecha4-1))
		mes=12
	else
		mes=$(($mes-1))
	fi ;
	if [ $mes -le 9 ]
	then
		mes='0'$mes
	fi ;
	fecha_ini=$fecha4$mes'01'
fi ;

echo "Inicio" >> xcuenta.log

#echo $mes
if [ $mes -eq 01 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 03 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 05 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 07 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 08 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 10 ]
then
   dia_fin=31
fi ;
if [ $mes -eq 12 ]
then
   dia_fin=31
fi ;

echo "Meses pares" >> xcuenta.log

if [ $mes -eq 04 ]
then
  dia_fin=30
fi ;
if [ $mes -eq 06 ]
then
  dia_fin=30
fi ;
if [ $mes -eq 09 ]
then
  dia_fin=30
fi ;
if [ $mes -eq 11 ]
then
  dia_fin=30
fi ;

if [ $mes -eq 02 ]
then
	 ano4=$(($ano/4))
	 ano_new=$(($ano4*4))
	 dif_ano=$(($ano - $ano_new))
	 if [ $dif_ano -eq 0 ]
	 then
   	dia_fin=29
	 else
   	dia_fin=28
	 fi ;
fi ;

echo "Parte 2" >> xcuenta.log

#echo $fecha6'01' $fecha8 $dia_fin
if [ $fecha6'01' -eq $fecha8 ]
then
	fecha8=$fecha4$mes$dia_fin
	fecha3=$fecha4$mes$dia_fin
else
	fecha_fin=$fecha6$dia_fin
	fecha3=$(($fecha8-1))
fi;

echo "Empieza la parte de cuenta" >> xcuenta.log

#echo $fecha_ini
#echo $fecha8
#echo $fecha3
#nohup xhlpcnt02_wwrl $fecha_ini $fecha8 $fecha3 &
#xhlpcnt02_wwrl $fecha_ini $fecha8 $fecha3

fi=$fecha_ini
ff=$fecha8
a=$fi

echo "Par metros: " $fecha_ini $fecha8 $fecha3 >> xcuenta.log

cd /home1/sigma/pre_unif/$fecha3 2>xerror
cta=`cat /home1/sigma/pre_unif/xerror | wc -l`
rm /home1/sigma/pre_unif/xerror

#echo $cta
if [ $cta -ge 1 ]
then
	 echo '!!!!ERROR, el directorio que quiere procesarse no existe!!!!' >> /home1/sigma/pre_unif/xcuenta.log
   exit
else
	 echo 'Directorio SI EXISTE, proceso continua sin problemas' >> /home1/sigma/pre_unif/xcuenta.log
fi ;

uncompress *
b=$fi
c=$ff
while [ b -le c ] ; do
   for file in * ; do
      r=`cut -c43-50 $file | grep $b | wc -l`
      t=`cat $file | wc -l`
      if [ $r -gt 0 ]
      then
         echo $fecha3'|'$file'|'$t'|'$r'|'$b >> /home1/sigma/pre_unif/cuenta_add_wwrl.$fecha_ini.$fecha8.$fecha3 
      fi ;
      done
   b=`expr $b + 1` ;
   done
compress *
echo 'Proceso termino OK!!!!!!!!' >> /home1/sigma/pre_unif/xcuenta.log


cd /home1/sigma/pre_unif
echo 'Proceso Finalizado' >> xcuenta.log
fecha_proceso=`date '+%d/%m/%Y %T'`
echo 'Fin del proceso: ' $fecha_proceso >> xcuenta.log
#exit
